### ISSUE TITLE
Bower Package does not exist

### ISSUE THREAD

**Issue by danielwarke** [Atmos206/ui-grid-custom-cell-select#5]
When I attempt to bower install ui-grid-custom-cell-select:
ENOTFOUND Package ui-grid-custom-cell-select not found
I also went searching on bower.io and found no results for this package.

**Comment by adeelasghar88** [comment]
Any update on this issue? I am also getting this error

**Comment by danielwarke** [comment]
No updates. I npm installed it instead of bower.
